一、创建ndarray数组

练习1：array()函数创建数组。通过列表或元组创建数组，数组的数据类型根据序列中元素的类型推导得出，数组以嵌套形式来表达数组的多维度概念。

In [8]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array((7,8,9,10))
c = np.array([[1,2,3,4],[7,8,9,10]])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


练习2：arange()函数创建数组。numpy中的arange()函数类似于内置函数range()，主要用于生成数组，在给定间隔内返回均匀间隔的数组。

In [9]:
b = np.arange(12).reshape(3,4)
c = b.ravel()
print(b)
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


练习3：eye()函数创建对角线为1的数组，其余的地方为0。

In [10]:
b = np.eye(4)
print(b)
c = b.reshape(2,8)
print(c)
d = np.eye(4, 7, k = 2, dtype = np.int64)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1.]]


练习4：ones()、zeros()函数创建元素为1、0的数组。

In [23]:
ones1 = np.ones((3,4), dtype = np.int32)
zeros1 = np.zeros((3,4))
print(ones1,zeros1)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]] [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


练习5：diag()函数创建数组。diag(x)，x可以为列表，元祖，一维或多为数组

In [21]:
a = np.arange(1,5)
b = [1,2,3,4]
c = (1,2,3,4)
d = np.arange(1,10).reshape(3, 3)
a = np.diag(a)  #把b,c,d都放进去查看区别，d放进去返回的是d的对角线元素

print(a,b,c,d)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]] [1, 2, 3, 4] (1, 2, 3, 4) [[1 2 3]
 [4 5 6]
 [7 8 9]]


练习6：random ()函数创建数组。numpy中的random模块中有很多可以产生随机数构成数组的函数，如生成随机整数、0-1内的浮点数等。

In [13]:
np.random.rand()  #随机生成[0, 1)之间的一个数
np.random.rand(2)  #随机生成一个[0, 1)之间的一维数组
np.random.rand(3,2)  #随机生成一个[0, 1)之间的二维数组
np.random.randint(3,size=3)  #生成3个[0, 3)之间的整数
np.random.randint(1,5)  #size=None,生成一个[1, 5)之间随机的一个整数
np.random.randint(1,5,size=(3,2))  #生成一个[1, 5)之间随机的一个二维数组
np.random.uniform()  #随机生成一个0-1.0的随机数
np.random.uniform(size=(3,2))   #随机生成一个数据是[0 -, 1.0)的二维数组
np.random.uniform(-1,1,size=10)  #随机生成一个[-1 , 1)的10个数的一维数组
np.random.uniform(5,10,size=(2, 3))  #随机生成一个[5 , 10) 的二维数组
np.random.randn()   #随机生成一个数
np.random.randn(1)  #随机生成一个一维数组
np.random.randn(3,2)  #随机生成一个二维数组

array([[-0.01371038,  1.70153599],
       [ 1.60607697,  0.61434498],
       [ 0.93334858,  2.6849194 ]])

练习7：创建数组的其他方式。

In [19]:
#创建具有指定数量元素的数组，并在指定的开始值和结束值之间平均间隔
array1 = np.linspace(2, 20, 8) 
# 在对数刻度上均匀分布的数字，刻度的开始和结束端点是某个底数的幂，通常为10
array2 = np.logspace(1, 2, num=10) 
#创建空的（3，3）的二维空数组
array3 = np.empty((3, 3))
#创建类似于array3的元素都为1的数组
array4 = np.ones_like(array3)
#创建类似于array3的元素都为0的数组
array5 = np.zeros_like(array3)
#创建类似于array3的元素都为6的数组
array6 = np.full_like(array3, 6)
#创建自定义数组形状及数值
array7 = np.full((2, 3), 6)


for i in range(1,7):
    array_name='array{}'.format(i)
    print(eval(array_name))

[ 2.          4.57142857  7.14285714  9.71428571 12.28571429 14.85714286
 17.42857143 20.        ]
[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]
[[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]]


二、数组属性、数组元素类型转换、改变数组形状

练习8：数组属性练习：ndim、shape、size、dtype。

In [25]:
c = np.array([[[1,2], [3,4]], [[5,6], [7,8]]], dtype = np.float64)
c.ndim
c.shape
c.size
c.dtype
print(c)

[[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]]


练习9：改变数组形状。

In [27]:
c.reshape(2,4)
c.resize(1,8)
print(c)

[[1. 2. 3. 4. 5. 6. 7. 8.]]


练习10：数组元素类型转换。

In [29]:
b=c.astype(np.int32)
print(b)

[[1 2 3 4 5 6 7 8]]


三、数组的切片和索引操作

练习11：一维数组的索引操作。

In [30]:
a = np.arange(1, 10)
print(a)  # 1 2 3 4 5 6 7 8 9
print(a[3])
print(a[-1])

[1 2 3 4 5 6 7 8 9]
4
9


练习12：多维数组的索引操作。

In [31]:
a = np.arange(1, 28)
a.resize(3,3,3)
print(a[1])
print(a[1][1])
print(a[1][1][1])

[[10 11 12]
 [13 14 15]
 [16 17 18]]
[13 14 15]
14


练习13：一维数组的切片操作。

In [32]:
a = np.arange(1, 10)
print(a)  # 1 2 3 4 5 6 7 8 9
print(a[:3])  # 1 2 3
print(a[3:6])   # 4 5 6
print(a[6:])  # 7 8 9
print(a[::-1])  # 9 8 7 6 5 4 3 2 1
print(a[::])  # 1 2 3 4 5 6 7 8 9
print(a[:])  # 1 2 3 4 5 6 7 8 9
print(a[::3])  # 1 4 7
print(a[1::3])  # 2 5 8
print(a[2::3])  # 3 6 9

[1 2 3 4 5 6 7 8 9]
[1 2 3]
[4 5 6]
[7 8 9]
[9 8 7 6 5 4 3 2 1]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 4 7]
[2 5 8]
[3 6 9]


练习14：多维数组的切片操作。

In [35]:
import numpy as np
a = np.arange(1, 28)
a.resize(3,3,3)
print(a)
print(a[0, 0, 0])
print(a[1, :, :])    #思考：如果是print(a[1:, :, :]) 则有什么区别？
print('区别',a[1:,:,:])
print(a[:, 1, :])
print(a[0, :, 1])
print(a[1:, :, 0:1])
print(a[1:][1])
print(a[1:][1][1])


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
1
[[10 11 12]
 [13 14 15]
 [16 17 18]]
区别 [[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[ 4  5  6]
 [13 14 15]
 [22 23 24]]
[2 5 8]
[[[10]
  [13]
  [16]]

 [[19]
  [22]
  [25]]]
[[19 20 21]
 [22 23 24]
 [25 26 27]]
[22 23 24]


四、数组的拼接和拆分操作

练习15：数组的拼接操作。

In [36]:
a = np.full((2, 3), 1)
b = np.full((2, 3), 6)
#垂直拼接
np.vstack((a, b))
#水平拼接
np.hstack((a, b))

array([[1, 1, 1, 6, 6, 6],
       [1, 1, 1, 6, 6, 6]])

练习16：数组的拆分操作。

In [37]:
c = np.arange(1, 13).reshape(3,4)
#按行拆分，c有3行
np.vsplit(c, 3)
s = np.vsplit(c, 3)
s[1]  # 查看一下s[1].shape
#按列拆分，a有4列
np.hsplit(c, 4)

[array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]]),
 array([[ 4],
        [ 8],
        [12]])]

五、数组的删除、复制、排序操作

练习17：数组的复制操作。

In [39]:
a = np.full((2, 3), 1)
b = a.view()
c = a.copy()  #深层复制，数据不共享
d = a
#查看a、b、c、d
print(a,b,c,d)
a[0] = 0
#查看a、b、c、d
print(a,b,c,d)

[[1 1 1]
 [1 1 1]] [[1 1 1]
 [1 1 1]] [[1 1 1]
 [1 1 1]] [[1 1 1]
 [1 1 1]]
[[0 0 0]
 [1 1 1]] [[0 0 0]
 [1 1 1]] [[1 1 1]
 [1 1 1]] [[0 0 0]
 [1 1 1]]


六、numpy数组计算及统计函数
练习18：数组的简单计算。

In [40]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a-b
a+b
a*b
a/b
a+1

array([2, 3, 4])

练习19：numpy常见统计函数：sum、min、max、mean、median、std、var等（不能直接求众数Mode）。

In [41]:
a = np.array([1,2,3,4])
# 求和、最小值、最大值
print(np.sum(a))
print(np.min(a))
print(np.max(a))

10
1
4


七、numpy综合练习题
1、创建一个四维数组，元素个数为120个，元素的值为整数，范围为1-100。

In [42]:
arr =np.random.randint(low=1,high=101,size=(2,3,4,5))
print(arr)

[[[[ 96  81  95   9  68]
   [ 18  50  63  54  47]
   [ 56  29  49  54  43]
   [ 96  70   4  11  12]]

  [[ 52  84  49  57  88]
   [ 95  46  73  92  87]
   [ 53  23 100   1   1]
   [ 65  51  80   9  90]]

  [[ 94   7  64  78  28]
   [  9  71  40  27  25]
   [ 93  73  29  83  51]
   [ 67  50  34   5  41]]]


 [[[ 21  42   6   1   3]
   [  8  78  70  45  49]
   [ 44  48   1  98  81]
   [ 39  65  49  78  36]]

  [[ 30  95  50  20  67]
   [ 67  87  36  17  88]
   [ 78  63  38  31  72]
   [ 19  76  30  80  96]]

  [[ 16   8  69  49  96]
   [ 64  70  88  25  79]
   [ 72  97   4  19  37]
   [ 12  44   3  13  83]]]]


2、生成一组范围在[0，1)内的2行2列的随机浮点数。

In [43]:
arr=np.random.rand(2,2)
print(arr)

[[0.80963811 0.13706106]
 [0.17972029 0.13441316]]


3、生成一组范围在[1，10)内的2行2列的随机整数。

In [44]:
arr=np.random.randint(1,10,(2,2))
print(arr)

[[1 3]
 [8 4]]


4、a = np.arange(1, 28).reshape(3,3,3)。请输出下图中的截取部门。

In [51]:
a = np.arange(1, 28).reshape(3,3,3)
b=a[1:,:,1]
print(b)

[[11 14 17]
 [20 23 26]]
